<?php
// Dados fictícios!
$funcionarios = [
    ['id' => 1, 'nome_completo' => 'Ana Silva', 'setor' => 'TI', 'cargo' => 'Analista', 'telefone' => '(11) 98765-4321', 'email' => 'ana.silva@empresa-show.net'],
    ['id' => 2, 'nome_completo' => 'Bruno Santos', 'setor' => 'RH', 'cargo' => 'Assistente', 'telefone' => '(21) 99876-5432', 'email' => 'bruno.santos@empresa-show.net'],
    ['id' => 3, 'nome_completo' => 'Carlos Oliveira', 'setor' => 'Financeiro', 'cargo' => 'Coordenador', 'telefone' => '(31) 91234-5678', 'email' => 'carlos.oliveira@empresa-show.net'],
    ['id' => 4, 'nome_completo' => 'Daniela Souza', 'setor' => 'Marketing', 'cargo' => 'Gerente', 'telefone' => '(41) 99988-7766', 'email' => 'daniela.souza@empresa-show.net'],
    ['id' => 5, 'nome_completo' => 'Eduardo Lima', 'setor' => 'Vendas', 'cargo' => 'Estagiário', 'telefone' => '(51) 98765-1234', 'email' => 'eduardo.lima@empresa-show.net'],
    ['id' => 6, 'nome_completo' => 'Fernanda Costa', 'setor' => 'Logística', 'cargo' => 'Supervisor', 'telefone' => '(61) 99632-1478', 'email' => 'fernanda.costa@empresa-show.net'],
    ['id' => 7, 'nome_completo' => 'Gabriel Gomes', 'setor' => 'Administrativo', 'cargo' => 'Diretor', 'telefone' => '(71) 98877-6655', 'email' => 'gabriel.gomes@empresa-show.net'],
    ['id' => 8, 'nome_completo' => 'Helena Martins', 'setor' => 'Jurídico', 'cargo' => 'Técnico', 'telefone' => '(81) 99785-4123', 'email' => 'helena.martins@empresa-show.net'],
    ['id' => 9, 'nome_completo' => 'Igor Rocha', 'setor' => 'Produção', 'cargo' => 'Consultor', 'telefone' => '(91) 98412-3698', 'email' => 'igor.rocha@empresa-show.net'],
    ['id' => 10, 'nome_completo' => 'Juliana Araújo', 'setor' => 'Suporte', 'cargo' => 'Operador', 'telefone' => '(12) 99123-4567', 'email' => 'juliana.araujo@empresa-show.net'],
    ['id' => 11, 'nome_completo' => 'Kleber Barbosa', 'setor' => 'TI', 'cargo' => 'Analista', 'telefone' => '(13) 99987-6543', 'email' => 'kleber.barbosa@empresa-show.net'],
    ['id' => 12, 'nome_completo' => 'Larissa Cardoso', 'setor' => 'RH', 'cargo' => 'Assistente', 'telefone' => '(14) 99234-5671', 'email' => 'larissa.cardoso@empresa-show.net'],
    ['id' => 13, 'nome_completo' => 'Marcos Ribeiro', 'setor' => 'Financeiro', 'cargo' => 'Coordenador', 'telefone' => '(15) 98876-5439', 'email' => 'marcos.ribeiro@empresa-show.net'],
    ['id' => 14, 'nome_completo' => 'Natália Mendes', 'setor' => 'Marketing', 'cargo' => 'Gerente', 'telefone' => '(16) 98789-1234', 'email' => 'natalia.mendes@empresa-show.net'],
    ['id' => 15, 'nome_completo' => 'Otávio Nunes', 'setor' => 'Vendas', 'cargo' => 'Estagiário', 'telefone' => '(17) 97654-3210', 'email' => 'otavio.nunes@empresa-show.net'],
    ['id' => 16, 'nome_completo' => 'Paula Carvalho', 'setor' => 'Logística', 'cargo' => 'Supervisor', 'telefone' => '(18) 96543-2109', 'email' => 'paula.carvalho@empresa-show.net'],
    ['id' => 17, 'nome_completo' => 'Rafael Monteiro', 'setor' => 'Administrativo', 'cargo' => 'Diretor', 'telefone' => '(19) 95432-1098', 'email' => 'rafael.monteiro@empresa-show.net'],
    ['id' => 18, 'nome_completo' => 'Sabrina Dias', 'setor' => 'Jurídico', 'cargo' => 'Técnico', 'telefone' => '(22) 94321-0987', 'email' => 'sabrina.dias@empresa-show.net'],
    ['id' => 19, 'nome_completo' => 'Thiago Castro', 'setor' => 'Produção', 'cargo' => 'Consultor', 'telefone' => '(24) 93210-9876', 'email' => 'thiago.castro@empresa-show.net'],
    ['id' => 20, 'nome_completo' => 'Vanessa Moraes', 'setor' => 'Suporte', 'cargo' => 'Operador', 'telefone' => '(27) 92109-8765', 'email' => 'vanessa.moraes@empresa-show.net'],
    ['id' => 21, 'nome_completo' => 'William Bezerra', 'setor' => 'TI', 'cargo' => 'Analista', 'telefone' => '(28) 91098-7654', 'email' => 'william.bezerra@empresa-show.net'],
    ['id' => 22, 'nome_completo' => 'Yasmin Farias', 'setor' => 'RH', 'cargo' => 'Assistente', 'telefone' => '(29) 90987-6543', 'email' => 'yasmin.farias@empresa-show.net'],
    ['id' => 23, 'nome_completo' => 'André Teixeira', 'setor' => 'Financeiro', 'cargo' => 'Coordenador', 'telefone' => '(32) 99876-5432', 'email' => 'andre.teixeira@empresa-show.net'],
    ['id' => 24, 'nome_completo' => 'Beatriz Cavalcanti', 'setor' => 'Marketing', 'cargo' => 'Gerente', 'telefone' => '(33) 98765-4321', 'email' => 'beatriz.cavalcanti@empresa-show.net'],
    ['id' => 25, 'nome_completo' => 'Caio Braga', 'setor' => 'Vendas', 'cargo' => 'Estagiário', 'telefone' => '(34) 97654-3210', 'email' => 'caio.braga@empresa-show.net'],
    ['id' => 26, 'nome_completo' => 'Débora Campos', 'setor' => 'Logística', 'cargo' => 'Supervisor', 'telefone' => '(35) 96543-2109', 'email' => 'debora.campos@empresa-show.net'],
    ['id' => 27, 'nome_completo' => 'Elton Vieira', 'setor' => 'Administrativo', 'cargo' => 'Diretor', 'telefone' => '(36) 95432-1098', 'email' => 'elton.vieira@empresa-show.net'],
    ['id' => 28, 'nome_completo' => 'Fábio Freitas', 'setor' => 'Jurídico', 'cargo' => 'Técnico', 'telefone' => '(37) 94321-0987', 'email' => 'fabio.freitas@empresa-show.net'],
    ['id' => 29, 'nome_completo' => 'Gisele Pinheiro', 'setor' => 'Produção', 'cargo' => 'Consultor', 'telefone' => '(38) 93210-9876', 'email' => 'gisele.pinheiro@empresa-show.net'],
    ['id' => 30, 'nome_completo' => 'Henrique Nogueira', 'setor' => 'Suporte', 'cargo' => 'Operador', 'telefone' => '(39) 92109-8765', 'email' => 'henrique.nogueira@empresa-show.net'],
    ['id' => 31, 'nome_completo' => 'Isabela Duarte', 'setor' => 'TI', 'cargo' => 'Analista', 'telefone' => '(42) 91098-7654', 'email' => 'isabela.duarte@empresa-show.net'],
    ['id' => 32, 'nome_completo' => 'João Macedo', 'setor' => 'RH', 'cargo' => 'Assistente', 'telefone' => '(43) 90987-6543', 'email' => 'joao.macedo@empresa-show.net'],
    ['id' => 33, 'nome_completo' => 'Karla Batista', 'setor' => 'Financeiro', 'cargo' => 'Coordenador', 'telefone' => '(44) 99876-5432', 'email' => 'karla.batista@empresa-show.net'],
    ['id' => 34, 'nome_completo' => 'Leonardo Viana', 'setor' => 'Marketing', 'cargo' => 'Gerente', 'telefone' => '(45) 98765-4321', 'email' => 'leonardo.viana@empresa-show.net'],
    ['id' => 35, 'nome_completo' => 'Mônica Fonseca', 'setor' => 'Vendas', 'cargo' => 'Estagiário', 'telefone' => '(46) 97654-3210', 'email' => 'monica.fonseca@empresa-show.net'],
    ['id' => 36, 'nome_completo' => 'Nícolas Aguiar', 'setor' => 'Logística', 'cargo' => 'Supervisor', 'telefone' => '(47) 96543-2109', 'email' => 'nicolas.aguiar@empresa-show.net'],
    ['id' => 37, 'nome_completo' => 'Olívia Lopes', 'setor' => 'Administrativo', 'cargo' => 'Diretor', 'telefone' => '(48) 95432-1098', 'email' => 'olivia.lopes@empresa-show.net'],
    ['id' => 38, 'nome_completo' => 'Pedro Marques', 'setor' => 'Jurídico', 'cargo' => 'Técnico', 'telefone' => '(49) 94321-0987', 'email' => 'pedro.marques@empresa-show.net'],
    ['id' => 39, 'nome_completo' => 'Quiteria Correia', 'setor' => 'Produção', 'cargo' => 'Consultor', 'telefone' => '(52) 93210-9876', 'email' => 'quiteria.correia@empresa-show.net'],
    ['id' => 40, 'nome_completo' => 'Renato Ramalho', 'setor' => 'Suporte', 'cargo' => 'Operador', 'telefone' => '(53) 92109-8765', 'email' => 'renato.ramalho@empresa-show.net'],
    ['id' => 41, 'nome_completo' => 'Sônia Tavares', 'setor' => 'TI', 'cargo' => 'Analista', 'telefone' => '(54) 91098-7654', 'email' => 'sonia.tavares@empresa-show.net'],
    ['id' => 42, 'nome_completo' => 'Tatiana Guimarães', 'setor' => 'RH', 'cargo' => 'Assistente', 'telefone' => '(55) 90987-6543', 'email' => 'tatiana.guimaraes@empresa-show.net'],
    ['id' => 43, 'nome_completo' => 'Ubiratan Borges', 'setor' => 'Financeiro', 'cargo' => 'Coordenador', 'telefone' => '(62) 99876-5432', 'email' => 'ubiratan.borges@empresa-show.net'],
    ['id' => 44, 'nome_completo' => 'Valéria Melo', 'setor' => 'Marketing', 'cargo' => 'Gerente', 'telefone' => '(63) 98765-4321', 'email' => 'valeria.melo@empresa-show.net'],
    ['id' => 45, 'nome_completo' => 'Wagner Xavier', 'setor' => 'Vendas', 'cargo' => 'Estagiário', 'telefone' => '(64) 97654-3210', 'email' => 'wagner.xavier@empresa-show.net'],
    ['id' => 46, 'nome_completo' => 'Amanda Leal', 'setor' => 'Logística', 'cargo' => 'Supervisor', 'telefone' => '(65) 96543-2109', 'email' => 'amanda.leal@empresa-show.net'],
    ['id' => 47, 'nome_completo' => 'Breno Ferreira', 'setor' => 'Administrativo', 'cargo' => 'Diretor', 'telefone' => '(66) 95432-1098', 'email' => 'breno.ferreira@empresa-show.net'],
    ['id' => 48, 'nome_completo' => 'Cláudia Almeida', 'setor' => 'Jurídico', 'cargo' => 'Técnico', 'telefone' => '(67) 94321-0987', 'email' => 'claudia.almeida@empresa-show.net'],
    ['id' => 49, 'nome_completo' => 'Diego Pereira', 'setor' => 'Produção', 'cargo' => 'Consultor', 'telefone' => '(68) 93210-9876', 'email' => 'diego.pereira@empresa-show.net'],
    ['id' => 50, 'nome_completo' => 'Erika Souza', 'setor' => 'Suporte', 'cargo' => 'Operador', 'telefone' => '(69) 92109-8765', 'email' => 'erika.souza@empresa-show.net']
];

$produtos = [
    ['id' => 1, 'nome' => 'Arroz Integral 1kg', 'preco' => 7.90, 'fabricante' => 'Tio João', 'qtd_estoque' => 150, 'lote' => 'A2025-01', 'validade' => '2026-08-15'],
    ['id' => 2, 'nome' => 'Feijão Carioca 1kg', 'preco' => 8.50, 'fabricante' => 'Camil', 'qtd_estoque' => 200, 'lote' => 'B2025-02', 'validade' => '2026-07-20'],
    ['id' => 3, 'nome' => 'Óleo de Soja 900ml', 'preco' => 6.99, 'fabricante' => 'Soya', 'qtd_estoque' => 180, 'lote' => 'C2025-03', 'validade' => '2026-06-10'],
    ['id' => 4, 'nome' => 'Macarrão Espaguete 500g', 'preco' => 3.75, 'fabricante' => 'Renata', 'qtd_estoque' => 300, 'lote' => 'D2025-04', 'validade' => '2027-05-30'],
    ['id' => 5, 'nome' => 'Açúcar Refinado 1kg', 'preco' => 4.20, 'fabricante' => 'União', 'qtd_estoque' => 220, 'lote' => 'E2025-05', 'validade' => '2027-04-12'],
    ['id' => 6, 'nome' => 'Leite Integral 1L', 'preco' => 5.49, 'fabricante' => 'Parmalat', 'qtd_estoque' => 90, 'lote' => 'F2025-06', 'validade' => '2025-12-05'],
    ['id' => 7, 'nome' => 'Café em Pó 250g', 'preco' => 12.90, 'fabricante' => 'Pilão', 'qtd_estoque' => 110, 'lote' => 'G2025-07', 'validade' => '2026-11-18'],
    ['id' => 8, 'nome' => 'Sabonete Líquido 200ml', 'preco' => 8.30, 'fabricante' => 'Dove', 'qtd_estoque' => 70, 'lote' => 'H2025-08', 'validade' => '2027-03-22'],
    ['id' => 9, 'nome' => 'Shampoo Anticaspa 400ml', 'preco' => 18.90, 'fabricante' => 'Clear', 'qtd_estoque' => 85, 'lote' => 'I2025-09', 'validade' => '2027-02-14'],
    ['id' => 10, 'nome' => 'Creme Dental 90g', 'preco' => 6.50, 'fabricante' => 'Colgate', 'qtd_estoque' => 130, 'lote' => 'J2025-10', 'validade' => '2026-09-30'],
    ['id' => 11, 'nome' => 'Papel Higiênico 4un', 'preco' => 9.99, 'fabricante' => 'Neve', 'qtd_estoque' => 250, 'lote' => 'K2025-11', 'validade' => '2028-01-10'],
    ['id' => 12, 'nome' => 'Detergente Líquido 500ml', 'preco' => 3.20, 'fabricante' => 'Ypê', 'qtd_estoque' => 320, 'lote' => 'L2025-12', 'validade' => '2027-06-25'],
    ['id' => 13, 'nome' => 'Sabão em Pó 1kg', 'preco' => 11.80, 'fabricante' => 'Omo', 'qtd_estoque' => 140, 'lote' => 'M2025-13', 'validade' => '2026-10-08'],
    ['id' => 14, 'nome' => 'Amaciante 2L', 'preco' => 14.50, 'fabricante' => 'Comfort', 'qtd_estoque' => 95, 'lote' => 'N2025-14', 'validade' => '2026-12-20'],
    ['id' => 15, 'nome' => 'Biscoito Recheado 140g', 'preco' => 2.99, 'fabricante' => 'Bono', 'qtd_estoque' => 400, 'lote' => 'O2025-15', 'validade' => '2026-04-05'],
    ['id' => 16, 'nome' => 'Suco de Laranja 1L', 'preco' => 7.80, 'fabricante' => 'Del Valle', 'qtd_estoque' => 120, 'lote' => 'P2025-16', 'validade' => '2025-11-30'],
    ['id' => 17, 'nome' => 'Refrigerante Cola 2L', 'preco' => 6.50, 'fabricante' => 'Coca-Cola', 'qtd_estoque' => 180, 'lote' => 'Q2025-17', 'validade' => '2026-03-15'],
    ['id' => 18, 'nome' => 'Cerveja Lata 350ml', 'preco' => 3.90, 'fabricante' => 'Skol', 'qtd_estoque' => 500, 'lote' => 'R2025-18', 'validade' => '2026-05-20'],
    ['id' => 19, 'nome' => 'Água Mineral 500ml', 'preco' => 1.80, 'fabricante' => 'Crystal', 'qtd_estoque' => 600, 'lote' => 'S2025-19', 'validade' => '2027-08-01'],
    ['id' => 20, 'nome' => 'Pão de Forma 500g', 'preco' => 5.90, 'fabricante' => 'Pullman', 'qtd_estoque' => 160, 'lote' => 'T2025-20', 'validade' => '2025-10-28'],
    ['id' => 21, 'nome' => 'Manteiga 200g', 'preco' => 9.90, 'fabricante' => 'Qualy', 'qtd_estoque' => 75, 'lote' => 'U2025-21', 'validade' => '2025-12-10'],
    ['id' => 22, 'nome' => 'Queijo Mussarela 200g', 'preco' => 12.50, 'fabricante' => 'Tirol', 'qtd_estoque' => 60, 'lote' => 'V2025-22', 'validade' => '2025-11-25'],
    ['id' => 23, 'nome' => 'Presunto Fatiado 150g', 'preco' => 8.70, 'fabricante' => 'Sadia', 'qtd_estoque' => 80, 'lote' => 'W2025-23', 'validade' => '2025-11-18'],
    ['id' => 24, 'nome' => 'Iogurte Natural 170g', 'preco' => 2.50, 'fabricante' => 'Nestlé', 'qtd_estoque' => 200, 'lote' => 'X2025-24', 'validade' => '2025-11-05'],
    ['id' => 25, 'nome' => 'Ovos Brancos 12un', 'preco' => 11.90, 'fabricante' => 'Granja Mantiqueira', 'qtd_estoque' => 100, 'lote' => 'Y2025-25', 'validade' => '2025-11-12'],
    ['id' => 26, 'nome' => 'Fralda Descartável P', 'preco' => 39.90, 'fabricante' => 'Pampers', 'qtd_estoque' => 45, 'lote' => 'Z2025-26', 'validade' => '2027-09-30'],
    ['id' => 27, 'nome' => 'Absorvente Noturno 8un', 'preco' => 7.50, 'fabricante' => 'Always', 'qtd_estoque' => 110, 'lote' => 'AA2025-27', 'validade' => '2028-02-15'],
    ['id' => 28, 'nome' => 'Pilhas AA 4un', 'preco' => 15.90, 'fabricante' => 'Duracell', 'qtd_estoque' => 90, 'lote' => 'BB2025-28', 'validade' => '2029-06-10'],
    ['id' => 29, 'nome' => 'Lâmpada LED 9W', 'preco' => 19.90, 'fabricante' => 'Philips', 'qtd_estoque' => 55, 'lote' => 'CC2025-29', 'validade' => '2030-12-31'],
    ['id' => 30, 'nome' => 'Desinfetante 1L', 'preco' => 8.90, 'fabricante' => 'Pinho Sol', 'qtd_estoque' => 130, 'lote' => 'DD2025-30', 'validade' => '2026-08-20']
];
?>
